### ISSUE TITLE
서버에 Redis 설치 건

### ISSUE THREAD

**Issue by busymidnight** [duck-map-project/duck-map-be#203]
## Description
> 로그아웃 및 jwt 토큰 사용을 위한 Redis 설치 요청

## To-do
- [x] 서버에 redis 설치 및 redis 서비스 실행

## ETC
- ec2에 redis 설치 및 실행 참고 글 입니다
  - https://velog.io/@ssoop/AWS-EC2%EC%97%90-Redis-%EC%84%A4%EC%B9%98
  - https://alsyean.tistory.com/51
  - https://choo.oopy.io/35c7ceb2-2bef-40c3-9033-251a47790007

- 배포용 application.yml에 추가해야할 내용
```
spring:
  redis:
    host: ec2주소
    port: 6379
```
